# -*- coding: utf-8 -*-
"""
Dataset build script 
==============================================================
Builds the stratified MIMIC-IV sample used across the entire project.

Section 2 (Data Understanding):
  - Joins discharge summaries to primary ICD diagnoses
  - Maps ICD codes → chapter labels (37 classes)
  - Stratified sample → data/mimic_icd_sample.csv

Section 3 (Data Preparation — AI Studio import):
  - Exports one-line TSV with tab separator and icd_chapter target column
  - Final AI Studio file: data/mimic_icd_for_ai_studio_oneline_v2.tsv

Run from this project folder:
    python section2_data_understanding/build_mimic_icd_sample.py

Requires local MIMIC-IV files.
"""
import os
import sys

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
_SHARED = os.path.join(PROJECT_ROOT, "shared")
sys.path.insert(0, _SHARED)
from paths import DATA_DIR, ensure_dirs

ensure_dirs()
_MIMIC_ROOT = os.path.abspath(os.path.join(PROJECT_ROOT, ".."))

import pandas as pd


# Paths — update _MIMIC_ROOT if  MIMIC files are stored elsewhere

OUT_DIR = DATA_DIR
os.makedirs(OUT_DIR, exist_ok=True)

DISCHARGE = os.path.join(
    _MIMIC_ROOT,
    "MMICIV",
    "mimic-iv-note-deidentified-free-text-clinical-notes-2.2",
    "note",
    "discharge.csv",
    "discharge.csv",
)
DIAGNOSES = os.path.join(_MIMIC_ROOT, "MMICIV", "diagnoses_icd.csv", "diagnoses_icd.csv")
D_ICD = os.path.join(_MIMIC_ROOT, "MMICIV", "d_icd_diagnoses.csv", "d_icd_diagnoses.csv")

# Target sample size and random seed 
SAMPLE_SIZE = 10_000
RANDOM_STATE = 42


def icd_chapter(code: str, version: int) -> str:
    """
    Convert a single ICD-9 or ICD-10 code into a chapter-level label.

    ICD-10: first letter of code  → e.g. I21 → ICD10-I (circulatory)
    ICD-9:  numeric range lookup  → e.g. 460-519 → ICD9-Respiratory
    """
    code = str(code).strip().upper()
    if version == 10:
        if not code:
            return "Unknown"
        if code[0].isalpha():
            return f"ICD10-{code[0]}"
        return "ICD10-Other"

    # ICD-9 chapter groups 
    if code.startswith("V"):
        return "ICD9-Supplementary-V"
    if code.startswith("E"):
        return "ICD9-Supplementary-E"
    digits = "".join(ch for ch in code if ch.isdigit())
    if not digits:
        return "ICD9-Other"
    n = int(digits[:3]) if len(digits) >= 3 else int(digits)
    ranges = [
        (1, 139, "ICD9-Infectious"),
        (140, 239, "ICD9-Neoplasms"),
        (240, 279, "ICD9-Endocrine"),
        (280, 289, "ICD9-Blood"),
        (290, 319, "ICD9-Mental"),
        (320, 389, "ICD9-Nervous"),
        (390, 459, "ICD9-Circulatory"),
        (460, 519, "ICD9-Respiratory"),
        (520, 579, "ICD9-Digestive"),
        (580, 629, "ICD9-Genitourinary"),
        (630, 679, "ICD9-Pregnancy"),
        (680, 709, "ICD9-Skin"),
        (710, 739, "ICD9-Musculoskeletal"),
        (740, 759, "ICD9-Congenital"),
        (760, 779, "ICD9-Perinatal"),
        (780, 799, "ICD9-Symptoms"),
        (800, 999, "ICD9-Injury"),
    ]
    for lo, hi, name in ranges:
        if lo <= n <= hi:
            return name
    return "ICD9-Other"


def flatten_for_rapidminer(text: str) -> str:
    """Make each discharge note a single physical line (no embedded newlines)."""
    text = str(text).replace("\r\n", " ").replace("\n", " ").replace("\r", " ")
    return text.replace('"', "'").strip()


def write_dataset_readme(export: pd.DataFrame) -> None:
    """Write / refresh data/mimic_icd_sample.README.txt alongside the CSV."""
    readme_path = os.path.join(OUT_DIR, "mimic_icd_sample.README.txt")
    n_rows = len(export)
    n_classes = export["label"].nunique()
    per_class = export["label"].value_counts().iloc[0] if n_rows else 0
    body = f"""data/mimic_icd_sample.csv — auto-generated documentation
=================================================

Generated by: section2_data_understanding/build_mimic_icd_sample.py
Rows: {n_rows:,}  |  Classes: {n_classes}  |  Per class: {per_class}

Columns
-------
text               Discharge summary (raw text input for classifiers)
label              ICD chapter target — 37 classes (e.g. ICD10-I, ICD9-Respiratory)
primary_icd_code   Primary ICD-9/ICD-10 code (seq_num = 1)
primary_icd_title  Diagnosis description from d_icd_diagnoses
note_id            Unique note identifier
hadm_id            Hospital admission ID (join key used at build time)

Load: pd.read_csv("data/mimic_icd_sample.csv")
Docs: data/mimic_icd_sample.README.txt in repository for full column notes.
"""
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"  mimic_icd_sample.README.txt  (column documentation)")


def main():
    # Step A: primary ICD label per admission 
    print("Step A: Loading primary ICD diagnoses (seq_num = 1)...")
    primary_parts = []
    for chunk in pd.read_csv(DIAGNOSES, chunksize=500_000):
        primary_parts.append(chunk[chunk["seq_num"] == 1].copy())
    primary = pd.concat(primary_parts, ignore_index=True)
    primary["icd_chapter"] = primary.apply(
        lambda r: icd_chapter(r["icd_code"], int(r["icd_version"])), axis=1
    )
    primary = primary.merge(
        pd.read_csv(D_ICD), on=["icd_code", "icd_version"], how="left"
    )

    # Step B: discharge summaries
    print("Step B: Loading discharge notes...")
    discharge_parts = []
    for chunk in pd.read_csv(DISCHARGE, usecols=["note_id", "hadm_id", "text"], chunksize=50_000):
        chunk = chunk.dropna(subset=["text"])
        chunk["text"] = chunk["text"].astype(str).str.strip()
        chunk = chunk[chunk["text"].str.len() > 100]  # drop trivially short notes
        discharge_parts.append(chunk)
    discharge = pd.concat(discharge_parts, ignore_index=True)

    # Step C: join text > label 
    print("Step C: Joining on hadm_id...")
    merged = discharge.merge(
        primary[["hadm_id", "icd_code", "icd_version", "long_title", "icd_chapter"]],
        on="hadm_id",
        how="inner",
    )
    print(f"  Joined records: {len(merged):,}")

    #  Step D: balanced stratified sample
    counts = merged["icd_chapter"].value_counts()
    keep = counts[counts >= 200].index
    merged = merged[merged["icd_chapter"].isin(keep)]
    per_class = max(50, SAMPLE_SIZE // merged["icd_chapter"].nunique())
    parts = [
        g.sample(n=min(len(g), per_class), random_state=RANDOM_STATE)
        for _, g in merged.groupby("icd_chapter")
    ]
    sample = pd.concat(parts, ignore_index=True)
    if len(sample) > SAMPLE_SIZE:
        sample = sample.sample(n=SAMPLE_SIZE, random_state=RANDOM_STATE).reset_index(drop=True)

    export = sample[
        ["text", "icd_chapter", "icd_code", "long_title", "note_id", "hadm_id"]
    ].rename(
        columns={
            "icd_chapter": "label",
            "icd_code": "primary_icd_code",
            "long_title": "primary_icd_title",
        }
    )

    # Step E: write Python + AI Studio files 
    
    # mimic_icd_sample.csv — main dataset (refer data/mimic_icd_sample.README.txt)
    #   text               : discharge summary (model input; raw text)
    #   label              : ICD chapter target (37 classes, e.g. ICD10-I)
    #   primary_icd_code   : original primary ICD code (seq_num = 1)
    #   primary_icd_title  : diagnosis title from d_icd_diagnoses
    #   note_id            : unique note identifier
    #   hadm_id            : admission join key used during dataset build
    
    print("Step E: Writing CSV / TSV exports...")
    paths = {
        "mimic_icd_sample.csv": export,
        "mimic_icd_for_ai_studio.csv": export[["text", "label"]],
    }
    for name, df in paths.items():
        df.to_csv(os.path.join(OUT_DIR, name), index=False, encoding="utf-8")
        print(f"  {name}: {len(df):,} rows")

    write_dataset_readme(export)

    # RapidMiner-friendly variants (Section 3.1 — import troubleshooting)
    studio = export[["text", "label"]].copy()
    studio["text"] = studio["text"].map(flatten_for_rapidminer)
    studio.to_csv(os.path.join(OUT_DIR, "mimic_icd_for_ai_studio_oneline.csv"), index=False, encoding="utf-8")
    studio.to_csv(os.path.join(OUT_DIR, "mimic_icd_for_ai_studio_oneline.tsv"), index=False, encoding="utf-8", sep="\t")

    # FINAL AI Studio file: tab-separated, one line per note, target column icd_chapter
    studio_v2 = studio.rename(columns={"label": "icd_chapter"})
    studio_v2.to_csv(
        os.path.join(OUT_DIR, "mimic_icd_for_ai_studio_oneline_v2.tsv"),
        index=False,
        encoding="utf-8",
        sep="\t",
    )
    print("  mimic_icd_for_ai_studio_oneline_v2.tsv  ← import THIS file in AI Studio")

    print("\nClass distribution (label):")
    print(export["label"].value_counts().sort_index().to_string())


if __name__ == "__main__":
    main()
